name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --ignore-platform-reqs --no-progress --no-suggest
      
    # Ignore COMPOSER CACHE stuff
    # - name: Cache Composer packages
    #   id: composer-cache
    #   uses: actions/cache@v3
    #   with:
    #     path: vendor
    #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-php-

    # - name: Install dependencies
    #   if: steps.composer-cache.outputs.cache-hit != 'true'
    #   #run: composer install --prefer-dist --no-progress --no-suggest
    #   run: composer install --ignore-platform-reqs --no-progress --no-suggest

    # # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer run-script test

    - name: Run phpmd code smell
      run: composer run-script smell

    - name: Run php-cs-fixer
      run: composer run-script fix

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: Apply php-cs-fixer changes
